-- MySQL Script generated by MySQL Workbench
-- 06/17/14 15:21:35
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qiuzudui
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qiuzudui` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `qiuzudui` ;

-- -----------------------------------------------------
-- Table `qiuzudui`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qiuzudui`.`city` (
  `idcity` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qiuzudui`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qiuzudui`.`school` (
  `idschool` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `idcity` INT NOT NULL,
  PRIMARY KEY (`idschool`),
  INDEX `city_idx` (`idcity` ASC),
  CONSTRAINT `city`
    FOREIGN KEY (`idcity`)
    REFERENCES `qiuzudui`.`city` (`idcity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qiuzudui`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qiuzudui`.`users` (
  `userName` VARCHAR(30) NOT NULL,
  `name` VARCHAR(45) NULL,
  `pwd` VARCHAR(45) NOT NULL,
  `sex` CHAR(1) NOT NULL,
  `qq` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `idschool` INT NULL,
  PRIMARY KEY (`userName`),
  INDEX `school` (`idschool` ASC),
  CONSTRAINT `school`
    FOREIGN KEY (`idschool`)
    REFERENCES `qiuzudui`.`school` (`idschool`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qiuzudui`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qiuzudui`.`message` (
  `idmessage` INT NOT NULL AUTO_INCREMENT,
  `cl1` VARCHAR(45) NOT NULL,
  `cl2` VARCHAR(45) NULL,
  `userName` VARCHAR(45) NOT NULL,
  `createTime` DATETIME NOT NULL,
  `time` VARCHAR(45) NULL,
  `title` VARCHAR(45) NOT NULL,
  `text` VARCHAR(200) NULL,
  `opt1` VARCHAR(100) NULL,
  `opt2` VARCHAR(100) NULL,
  `opt3` VARCHAR(100) NULL,
  PRIMARY KEY (`idmessage`),
  INDEX `classification` (`cl1` ASC, `cl2` ASC),
  INDEX `user` (`userName` ASC),
  INDEX `createTime` (`createTime` ASC),
  CONSTRAINT `user`
    FOREIGN KEY (`userName`)
    REFERENCES `qiuzudui`.`users` (`userName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
